#!/bin/bash

export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# keybindings daemon
######### PUT YOUR PERSONAL KEYBINDS INSIDE YOUR THEME AND ADD THOSE THE THE STANDARD KEYBINDS ######
######### JUST BE AWARE : DOUBLE KEYBINDS WILL RESULT IN A CRASH!!!!!!!! ##########
if [ -f "$SCRIPTPATH/sxhkd/sxhkdrc-personal" ] ; then
  # check if there is a keybinds-folder inside your personal theme and use it
  sxhkd -c  ~/.config/leftwm/sxhkd/sxhkdrc $SCRIPTPATH/sxhkd/sxhkdrc-personal &
else
  # standard keybinds
  sxhkd -c  ~/.config/leftwm/sxhkd/sxhkdrc &
fi  

# diversity of apps to start
nm-applet &
pamac-tray &
xfce4-power-manager &
numlockx on &
blueberry-tray &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/lib/xfce4/notifyd/xfce4-notifyd &
volumeicon &
#conky -c ~/.config/leftwm/system-overview &
#nitrogen --restore &
#caffeine &
#vivaldi-stable &
#firefox &
#thunar &
#dropbox &
#insync start &
#discord &
#spotify &
#atom &

# Boot picom or compton if it exists
if [ -x "$(command -v picom)" ]; then
  picom --config "$SCRIPTPATH"/picom.conf &> /dev/null &
  #picom --config $HOME/.config/leftwm/themes/current/picom.conf --experimental-backends &> /dev/null &
  #picom &> /dev/null &
  #picom --experimental-backends &> /dev/null &
elif [ -x "$(command -v compton)" ]; then
  compton --config $HOME/.config/leftwm/themes/current/compton.conf &> /dev/null &
fi

#Set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"

# Set background
if [ -x "$(command -v feh)" ]; then
  feh --randomize --bg-fill /usr/share/backgrounds/*
fi

#mainbar
index=0
monitors=($(polybar -m | sed s/:.*//))
leftwm-state -q -n -t "$SCRIPTPATH"/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
  barname="mainbar$index"
  monitor=${monitors[index]} width=$(( width - 16 )) polybar -c "$SCRIPTPATH"/polybar/polybartop.config $barname &> /dev/null &
  monitor=${monitors[index]} width=$(( width - 16 )) polybar -c "$SCRIPTPATH"/polybar/polybarbottom.config $barname &> /dev/null &
  let index=index+1
done
